/**
 * Auto-generated by scripts/build-wrappers.mjs.
 * This is a lightweight npm-backed wrapper, not an inlined self-contained build.
 */

import '@livingdesign/react/dist/styles.css';

export {
  Spinner
} from '@livingdesign/react';
