// Default values for campaign fields
export const addDefaultCampaignFields = (campaign: any) => ({
  ...campaign,
  startDate: campaign.startDate || "10/01/2024",
  endDate: campaign.endDate || "No end date",
  suggestedTotalBudget: campaign.suggestedTotalBudget || "-",
  suggestedDailyBudget: campaign.suggestedDailyBudget || "-",
  roasTarget: campaign.roasTarget || "-",
  recommendedRoasTarget: campaign.recommendedRoasTarget || "-",
  campaignType: campaign.campaignType || "Sponsored Products (Auto)",
  avgCapOutTime: campaign.avgCapOutTime || "10:00am PST",
  estMissedImpressions: campaign.estMissedImpressions || "-",
  estMissedClicks: campaign.estMissedClicks || "-",
  campaignReviewStatus: campaign.campaignReviewStatus || "Approved",
  roas: campaign.roas || "10.50",
  totalAttributedSales: campaign.totalAttributedSales || "$25,000",
  impressions: campaign.impressions || "500,000",
  clicks: campaign.clicks || "2,500",
  ctr: campaign.ctr || "0.50%",
  totalProductDetailPageViews: campaign.totalProductDetailPageViews || "2,000",
  totalAddToCart: campaign.totalAddToCart || "800",
  conversionRate: campaign.conversionRate || "8.00%",
  orders: campaign.orders || "150",
  unitsSold: campaign.unitsSold || "200",
});
